# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a14dc40388a81ab4ab2af1c2f7a220c43311634c7a9a79e7a431151afa9f5c91b795641d43a72643d36f7a95257343bf56d1f43ce493d63b9a71652f4e1c409

test:
  secret_key_base: 970c2123f75eed482638cb303a9f4c9d79ca4517565a3805a1bb634198f378fbc99f8810ba1e19c8f22967abf20d7ebe877deefcce8a55be7739b9578e15ea5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
